#!/bin/bash

start_service() {
    # TODO
    :
}

stop_service() {
    # TODO
    :
}

case $1 in
    "start") start_service ;;
    "stop") stop_service ;;
    *) echo "Usage: $0 start|stop" ;;
esac
